### ISSUE TITLE
Pure CMake approach

### ISSUE THREAD

**Issue by cpp-entwickler-de** [daixtrose/cmake_utilities#2]
This is a demo that handles dependencies purely in CMake by reading dependencies.txt files from the root directory of a project (and recursively for all listed dependencies). It only requires git and a non-ancient CMake version (> 3.19) to be installed.

The dependencies.txt format is `repo-uri revision [subdirectory]` with one dependency per line. `revision` can be anything that can be checked out by git. `subdirectory` is optional in case the dependencies.txt or CMakeLists.txt file are not in the git root.

The RepoMan module can be either included in CMake projects or be called by its name on the command line inside a non-CMake project. The demo projects already include it, but it can also be called via command line while within any project directory. The only difference is that the latter will not configure/generate a project.

[repoman.zip](https://github.com/daixtrose/cmake_utilities/files/11654616/repoman.zip)

**Comment by cpp-entwickler-de** [comment]
New Test Projects

[repoman.zip](https://github.com/daixtrose/cmake_utilities/files/11748849/repoman.zip)

**Comment by daixtrose** [comment]
Superceded by https://github.com/dep-heaven/tool_1/
